import os

TWEET_TEXT_COLUMN = 0
TWEET_STATE_COLUMN = 1

SENTIMENT_DICTIONARY_NAME = "dictionary_final.csv"
SENTIMENT_DICTIONARY_DIR = "sentiment_analyzer_lib"

SENTIMENT_DICTIONARY = os.path.join(SENTIMENT_DICTIONARY_DIR,SENTIMENT_DICTIONARY_NAME)

